mv 01-trees-introduction.md 01-treetraversal-introduction.md
mv 01-trees-introduction-slides.md 01-treetraversal-introduction-slides.md
mv 02-trees-termsI.md 02-treetraversal-termsI.md
mv 02-trees-termsI-slides.md 02-treetraversal-termsI-slides.md
mv 03-trees-termsII.md 03-treetraversal-termsII.md
mv 03-trees-termsII-slides.md 03-treetraversal-termsII-slides.md
mv 04-trees-recursion.md 04-treetraversal-recursion.md
mv 04-trees-recursion-slides.md 04-treetraversal-recursion-slides.md
mv 05-trees-termsIII.md 05-treetraversal-termsIII.md
mv 05-trees-termsIII-slides.md 05-treetraversal-termsIII-slides.md
mv 06-trees-preorder.md 06-treetraversal-preorder.md
mv 06-trees-preorder-slides.md 06-treetraversal-preorder-slides.md
mv 07-trees-postorder.md 07-treetraversal-postorder.md
mv 07-trees-postorder-slides.md 07-treetraversal-postorder-slides.md
mv 08-trees-getters.md 08-treetraversal-getters.md
mv 08-trees-getters-slides.md 08-treetraversal-getters-slides.md
mv 09-trees-relationships.md 09-treetraversal-relationships.md
mv 09-trees-relationships-slides.md 09-treetraversal-relationships-slides.md
mv 10-trees-traversal-code.md 10-treetraversal-traversal-code.md
mv 10-trees-traversal-code-slides.md 10-treetraversal-traversal-code-slides.md