touch 01-tries-introduction.md
touch 01-tries-introduction-slides.md
touch 02-tries-add-word.md
touch 02-tries-add-word-slides.md
touch 03-tries-remove-word.md
touch 03-tries-remove-word-slides.md
touch 04-tries-contains-word.md
touch 04-tries-contains-word-slides.md
touch 05-tries-completions.md
touch 05-tries-completions-slides.md
touch 06-tries-word-functions.md
touch 06-tries-word-functions-slides.md