touch 01-Performance-introduction.md
touch 01-Performance-introduction-slides.md
touch 02-Performance-trees.md
touch 02-Performance-trees-slides.md
touch 03-Performance-graphs.md
touch 03-Performance-graphs-slides.md
touch 04-Performance-PQs.md
touch 04-Performance-PQs-slides.md
touch 05-Performance-tree-algs.md
touch 05-Performance-tree-algs-slides.md
touch 06-Performance-graph-algs.md
touch 06-Performance-graph-algs-slides.md