touch 03-trees-not-tree.md
touch 03-trees-not-tree-slides.md
touch 04-trees-pseudocode.md
touch 04-trees-pseudocode-slides.md
touch 05-trees-add-child.md
touch 05-trees-add-child-slides.md
touch 06-trees-remove-child.md
touch 06-trees-remove-child-slides.md
touch 07-trees-getters.md
touch 07-trees-getters-slides.md